### ISSUE TITLE
Circle back on `pytest.PytestUnraisableExceptionWarning`

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#237]
We currently suppress some `pytest.PytestUnraisableExceptionWarning` warnings in the `.pytest.ini` file.

We should do a deeper dive to ensure this will not impact users.

## Logs
```sh
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/tempfile.py", line 934, in _cleanup
    _warnings.warn(warn_message, ResourceWarning)
ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/crm_artifact_fetcher_ohazv3ax_dummy_project_failure'>
...Exception ignored in: <finalize object at 0x7f90195b0b80; dead>
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/tempfile.py", line 934, in _cleanup
    _warnings.warn(warn_message, ResourceWarning)
ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/crm_artifact_fetcher_jcfnl6of_dummy_project_failure'>
.Exception ignored in: <finalize object at 0x7f90195b11c0; dead>
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/tempfile.py", line 934, in _cleanup
    _warnings.warn(warn_message, ResourceWarning)
ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/crm_artifact_fetcher_r8qs6r9e_dummy_project_failure'>
...Exception ignored in: <finalize object at 0x7f9019a59840; dead>
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/tempfile.py", line 934, in _cleanup
    _warnings.warn(warn_message, ResourceWarning)
ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/crm_artifact_fetcher_q6gxo6db_dummy_project_failure'>
...Exception ignored in: <finalize object at 0x7f90195b1cc0; dead>
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/tempfile.py", line 934, in _cleanup
    _warnings.warn(warn_message, ResourceWarning)
ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/crm_artifact_fetcher_uvbn7eq7_dummy_project_failure'>
...Exception ignored in: <finalize object at 0x7f90195b2e80; dead>
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/conda-recipe-manager/lib/python3.11/tempfile.py", line 934, in _cleanup
    _warnings.warn(warn_message, ResourceWarning)
ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/crm_artifact_fetcher_[79](https://github.com/conda-incubator/conda-recipe-manager/actions/runs/11748711758/job/32733387234?pr=235#step:4:80)bk26ao_dummy_project_failure'>
```

## NOTES
- This seems tied to the complex mockers used in the `fetcher` module. May also be related to our `pyfakefs` usage?
- Docs: https://docs.pytest.org/en/stable/reference/reference.html#pytest.PytestUnraisableExceptionWarning

**Comment by mrbean-bremen** [comment]
FWIW, I had a look at these too (in case they are related to pyfakefs), but as far as I can see they stem from the tempfile created in `BaseArtifactFetcher`. Removing the usage of pyfakefs in the affected tests does not remove the warnings.
If for example in _test_git_artifact_fetcher.py_ change the fixture from
```py
@pytest.fixture(name="git_fetcher_failure")
def fixture_git_fetcher_failure() -> GitArtifactFetcher:
    return GitArtifactFetcher("dummy_project_failure", "")
```
to 
```py
@pytest.fixture(name="git_fetcher_failure")
def fixture_git_fetcher_failure() -> Generator[GitArtifactFetcher]:
    fetcher = GitArtifactFetcher("dummy_project_failure", "")
    yield fetcher
    fetcher._temp_dir.cleanup()
```
the warning goes away, at least locally for me.
